
// This file has been generated by the GUI designer. Do not modify.
namespace NETGenVisualizer
{
	public partial class VisualizerControl
	{
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Label label1;
		private global::Gtk.FileChooserButton fileChooserNetworkFile;
		private global::Gtk.Label label5;
		private global::Gtk.Label label6;
		private global::Gtk.Entry entryEdgeWidthExpression;
		private global::Gtk.Label label7;
		private global::Gtk.FileChooserButton fileChooserCEFFile;
		private global::Gtk.Label label8;
		private global::Gtk.Entry entrySearchNode;
		private global::Gtk.Label label9;
		private global::Gtk.FileChooserButton fileChooserHighlightNodes;
		private global::Gtk.FileChooserButton fileChooserExportPDF;
		private global::Gtk.Label label10;
		private global::Gtk.FileChooserButton fileChooserExportBitmap;
		private global::Gtk.Label label11;
		private global::Gtk.Entry entryNodeSizeExpression;
		private global::Gtk.Button btnApplyNodeSize;
		private global::Gtk.Button btnApplyEdgeWidth;
		private global::Gtk.Button btnSearch;
		private global::Gtk.Button btnRunCEF;
		private global::Gtk.FileChooserButton fileChooserCEFFrames;
		private global::Gtk.Label label3;
		private global::Gtk.ColorButton btnChoseDefaultNodeColor;
		private global::Gtk.ColorButton btnChoseEdgeColor;
		private global::Gtk.Label label4;
		private global::Gtk.Entry entry4;
		private global::Gtk.Button btnComputeLayout;
		private global::Gtk.ColorButton btnChoseHighlightNodeColor;
		private global::Gtk.Button btnResetHighlights;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NETGenVisualizer.VisualizerControl
			this.Name = "NETGenVisualizer.VisualizerControl";
			this.Title = global::Mono.Unix.Catalog.GetString ("VisualizerControl");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child NETGenVisualizer.VisualizerControl.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Network File");
			this.fixed1.Add (this.label1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
			w1.X = 9;
			w1.Y = 11;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.fileChooserNetworkFile = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select A File"), ((global::Gtk.FileChooserAction)(0)));
			this.fileChooserNetworkFile.WidthRequest = 120;
			this.fileChooserNetworkFile.Name = "fileChooserNetworkFile";
			this.fileChooserNetworkFile.ShowHidden = true;
			this.fixed1.Add (this.fileChooserNetworkFile);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.fileChooserNetworkFile]));
			w2.X = 98;
			w2.Y = 3;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Node Size");
			this.fixed1.Add (this.label5);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
			w3.X = 8;
			w3.Y = 104;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Edge Width");
			this.fixed1.Add (this.label6);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label6]));
			w4.X = 8;
			w4.Y = 133;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entryEdgeWidthExpression = new global::Gtk.Entry ();
			this.entryEdgeWidthExpression.WidthRequest = 300;
			this.entryEdgeWidthExpression.CanFocus = true;
			this.entryEdgeWidthExpression.Name = "entryEdgeWidthExpression";
			this.entryEdgeWidthExpression.Text = global::Mono.Unix.Catalog.GetString ("0.1f");
			this.entryEdgeWidthExpression.IsEditable = true;
			this.entryEdgeWidthExpression.InvisibleChar = '●';
			this.fixed1.Add (this.entryEdgeWidthExpression);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryEdgeWidthExpression]));
			w5.X = 96;
			w5.Y = 129;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Cuttlefish cef");
			this.fixed1.Add (this.label7);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label7]));
			w6.X = 7;
			w6.Y = 164;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.fileChooserCEFFile = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select A File"), ((global::Gtk.FileChooserAction)(0)));
			this.fileChooserCEFFile.WidthRequest = 120;
			this.fileChooserCEFFile.Name = "fileChooserCEFFile";
			this.fileChooserCEFFile.ShowHidden = true;
			this.fixed1.Add (this.fileChooserCEFFile);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.fileChooserCEFFile]));
			w7.X = 94;
			w7.Y = 156;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Search Node");
			this.fixed1.Add (this.label8);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label8]));
			w8.X = 7;
			w8.Y = 192;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entrySearchNode = new global::Gtk.Entry ();
			this.entrySearchNode.WidthRequest = 300;
			this.entrySearchNode.CanFocus = true;
			this.entrySearchNode.Name = "entrySearchNode";
			this.entrySearchNode.IsEditable = true;
			this.entrySearchNode.InvisibleChar = '●';
			this.fixed1.Add (this.entrySearchNode);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entrySearchNode]));
			w9.X = 95;
			w9.Y = 187;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Highlight ... ");
			this.fixed1.Add (this.label9);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label9]));
			w10.X = 6;
			w10.Y = 219;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.fileChooserHighlightNodes = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select A File"), ((global::Gtk.FileChooserAction)(0)));
			this.fileChooserHighlightNodes.WidthRequest = 120;
			this.fileChooserHighlightNodes.Name = "fileChooserHighlightNodes";
			this.fixed1.Add (this.fileChooserHighlightNodes);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.fileChooserHighlightNodes]));
			w11.X = 95;
			w11.Y = 213;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.fileChooserExportPDF = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Export PDF File ... "), ((global::Gtk.FileChooserAction)(0)));
			this.fileChooserExportPDF.WidthRequest = 120;
			this.fileChooserExportPDF.Name = "fileChooserExportPDF";
			this.fixed1.Add (this.fileChooserExportPDF);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.fileChooserExportPDF]));
			w12.X = 94;
			w12.Y = 245;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Export PDF");
			this.fixed1.Add (this.label10);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label10]));
			w13.X = 10;
			w13.Y = 248;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.fileChooserExportBitmap = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select A File"), ((global::Gtk.FileChooserAction)(0)));
			this.fileChooserExportBitmap.WidthRequest = 120;
			this.fileChooserExportBitmap.Name = "fileChooserExportBitmap";
			this.fixed1.Add (this.fileChooserExportBitmap);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.fileChooserExportBitmap]));
			w14.X = 93;
			w14.Y = 276;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Export Bitmap");
			this.fixed1.Add (this.label11);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label11]));
			w15.X = 4;
			w15.Y = 281;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entryNodeSizeExpression = new global::Gtk.Entry ();
			this.entryNodeSizeExpression.WidthRequest = 300;
			this.entryNodeSizeExpression.CanFocus = true;
			this.entryNodeSizeExpression.Name = "entryNodeSizeExpression";
			this.entryNodeSizeExpression.Text = global::Mono.Unix.Catalog.GetString ("2f");
			this.entryNodeSizeExpression.IsEditable = true;
			this.entryNodeSizeExpression.InvisibleChar = '●';
			this.fixed1.Add (this.entryNodeSizeExpression);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryNodeSizeExpression]));
			w16.X = 97;
			w16.Y = 100;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnApplyNodeSize = new global::Gtk.Button ();
			this.btnApplyNodeSize.CanFocus = true;
			this.btnApplyNodeSize.Name = "btnApplyNodeSize";
			this.btnApplyNodeSize.UseUnderline = true;
			this.btnApplyNodeSize.Label = global::Mono.Unix.Catalog.GetString ("Apply");
			this.fixed1.Add (this.btnApplyNodeSize);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnApplyNodeSize]));
			w17.X = 404;
			w17.Y = 96;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnApplyEdgeWidth = new global::Gtk.Button ();
			this.btnApplyEdgeWidth.CanFocus = true;
			this.btnApplyEdgeWidth.Name = "btnApplyEdgeWidth";
			this.btnApplyEdgeWidth.UseUnderline = true;
			this.btnApplyEdgeWidth.Label = global::Mono.Unix.Catalog.GetString ("Apply");
			this.fixed1.Add (this.btnApplyEdgeWidth);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnApplyEdgeWidth]));
			w18.X = 402;
			w18.Y = 127;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnSearch = new global::Gtk.Button ();
			this.btnSearch.CanFocus = true;
			this.btnSearch.Name = "btnSearch";
			this.btnSearch.UseUnderline = true;
			this.btnSearch.Label = global::Mono.Unix.Catalog.GetString ("Search");
			this.fixed1.Add (this.btnSearch);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnSearch]));
			w19.X = 402;
			w19.Y = 185;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnRunCEF = new global::Gtk.Button ();
			this.btnRunCEF.CanFocus = true;
			this.btnRunCEF.Name = "btnRunCEF";
			this.btnRunCEF.UseUnderline = true;
			this.btnRunCEF.Label = global::Mono.Unix.Catalog.GetString ("Run ...");
			this.fixed1.Add (this.btnRunCEF);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnRunCEF]));
			w20.X = 220;
			w20.Y = 156;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.fileChooserCEFFrames = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select A File"), ((global::Gtk.FileChooserAction)(0)));
			this.fileChooserCEFFrames.WidthRequest = 120;
			this.fileChooserCEFFrames.Name = "fileChooserCEFFrames";
			this.fileChooserCEFFrames.ShowHidden = true;
			this.fixed1.Add (this.fileChooserCEFFrames);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.fileChooserCEFFrames]));
			w21.X = 283;
			w21.Y = 155;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Node Color");
			this.fixed1.Add (this.label3);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
			w22.X = 7;
			w22.Y = 72;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnChoseDefaultNodeColor = new global::Gtk.ColorButton ();
			this.btnChoseDefaultNodeColor.CanFocus = true;
			this.btnChoseDefaultNodeColor.Events = ((global::Gdk.EventMask)(784));
			this.btnChoseDefaultNodeColor.Name = "btnChoseDefaultNodeColor";
			this.fixed1.Add (this.btnChoseDefaultNodeColor);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnChoseDefaultNodeColor]));
			w23.X = 95;
			w23.Y = 62;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnChoseEdgeColor = new global::Gtk.ColorButton ();
			this.btnChoseEdgeColor.CanFocus = true;
			this.btnChoseEdgeColor.Events = ((global::Gdk.EventMask)(784));
			this.btnChoseEdgeColor.Name = "btnChoseEdgeColor";
			this.fixed1.Add (this.btnChoseEdgeColor);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnChoseEdgeColor]));
			w24.X = 272;
			w24.Y = 60;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Edge Color");
			this.fixed1.Add (this.label4);
			global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
			w25.X = 193;
			w25.Y = 65;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry4 = new global::Gtk.Entry ();
			this.entry4.WidthRequest = 300;
			this.entry4.CanFocus = true;
			this.entry4.Name = "entry4";
			this.entry4.Text = global::Mono.Unix.Catalog.GetString ("FruchtermanReingoldLayout(5)");
			this.entry4.IsEditable = true;
			this.entry4.InvisibleChar = '●';
			this.fixed1.Add (this.entry4);
			global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry4]));
			w26.X = 5;
			w26.Y = 34;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnComputeLayout = new global::Gtk.Button ();
			this.btnComputeLayout.CanFocus = true;
			this.btnComputeLayout.Name = "btnComputeLayout";
			this.btnComputeLayout.UseUnderline = true;
			this.btnComputeLayout.Label = global::Mono.Unix.Catalog.GetString ("Apply");
			this.fixed1.Add (this.btnComputeLayout);
			global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnComputeLayout]));
			w27.X = 309;
			w27.Y = 33;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnChoseHighlightNodeColor = new global::Gtk.ColorButton ();
			this.btnChoseHighlightNodeColor.CanFocus = true;
			this.btnChoseHighlightNodeColor.Events = ((global::Gdk.EventMask)(784));
			this.btnChoseHighlightNodeColor.Name = "btnChoseHighlightNodeColor";
			this.fixed1.Add (this.btnChoseHighlightNodeColor);
			global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnChoseHighlightNodeColor]));
			w28.X = 220;
			w28.Y = 212;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnResetHighlights = new global::Gtk.Button ();
			this.btnResetHighlights.CanFocus = true;
			this.btnResetHighlights.Name = "btnResetHighlights";
			this.btnResetHighlights.UseUnderline = true;
			this.btnResetHighlights.Label = global::Mono.Unix.Catalog.GetString ("Reset");
			this.fixed1.Add (this.btnResetHighlights);
			global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnResetHighlights]));
			w29.X = 281;
			w29.Y = 215;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 684;
			this.DefaultHeight = 365;
			this.Show ();
		}
	}
}
